DefinedNet/nebula-docs

README.md
package-lock.json
package.json
src/components/LeftSidebar/LeftSidebar.astro
src/components/MobileNav.astro
src/data/config-reference.md
src/data/docs/en/advanced.md
src/data/docs/en/cli.md
src/data/docs/en/guides.md
src/data/docs/en/logs.md
src/data/docs/en/nebula.md
src/data/docs/en/overview.md
src/data/docs/en/quick-start.md
src/data/docs/en/run-as-service.md
src/data/docs/en/unsafe_routes.md
src/data/settings/sidebar.json
src/get-page-links.ts
src/pages/index.astro
src/scripts/cms/index.ts
src/scripts/cms/netlify-cms-config.ts
src/styles/button.scss
src/styles/typography.scss

This organizes our pages into three main sections, Overview, Guides, and Configuration Reference
The styles here don't matter too much, since they won't be used on defined.net where they'll be published.  
Organizing the pages into sections can be done via the CMS:

Add sections to navigation

---

src/data/docs/en/guides.md
src/data/docs/en/unsafe_routes.md

this fixes links on defined.net/nebula, but breaks the relative links in this repo.
TODO make it work for both

quick fix to relative links

---

src/components/LeftSidebar/LeftSidebar.astro

This fixes an issue identified by @briankelly in https://github.com/DefinedNet/nebula-docs/pull/15#discussion_r773477740.

Fix highlighting of sidebar sub-items

---

astro.config.mjs
package-lock.json
package.json
src/components/HeadCommon.astro
src/components/MobileNav.astro
src/components/RightSidebar/RightSidebar.astro
src/layouts/MainLayout.astro
src/pages/admin.astro
src/pages/nebula/[locale]/[slug].astro
src/pages/nebula/[slug].astro

This updates to the latest 1.0.0 beta version of Astro, and fixes a few issues left over from the previous migration to 0.26.

Upgrade astro to 1.0.0-beta.24

---

.prettierrc.yaml
package-lock.json
package.json

This adds prettier + `format` and `format:check` scripts
This was adding a prettier check in CI, but that's paused on having Github Actions enabled in the repo

Adds `prettier`, `prettier-plugin-astro`, `prettier-plugin-sort-imports`

---

.prettierrc.yaml
package-lock.json
package.json
public/make-scrollable-code-focusable.js
src/components/ConfigOption.astro
src/components/ConfigReference.astro
src/components/HeadCommon.astro
src/components/Header/Header.astro
src/components/Header/LanguageSelect.tsx
src/components/Header/SkipToContent.astro
src/components/LeftSidebar/LeftSidebar.astro
src/components/MobileNav.astro
src/components/Nav/NavLink.astro
src/components/PageContent/PageContent.astro
src/components/Redirect.astro
src/components/RightSidebar/TOC.astro
src/config.ts
src/data/docs/en/config.md
src/get-page-links.ts
src/languages.ts
src/layouts/MainLayout.astro
src/pages/admin.astro
src/pages/nebula/[locale]/[slug].astro
src/pages/nebula/[slug].astro
src/scripts/cms/index.ts
src/scripts/cms/netlify-cms-config.ts
src/styles/theme.scss
tsconfig.json

This PR is based on #29 and runs `npm run format` on all the code

Format all the code!

---

src/data/config-reference.md

Add a hint on how to generate SSH host key

---

astro.config.mjs
package-lock.json
package.json
src/components/ConfigOption.astro
src/components/HeadCommon.astro
src/components/LeftSidebar/LeftSidebar.astro
src/styles/button.scss
src/styles/code.scss
src/styles/global.scss
src/styles/layout.scss
src/styles/theme.scss
src/styles/typography.scss

This brings the styles here in local dev into line with those on the final defined.net website.

Sync styles with defined.net

---

package-lock.json
src/data/config-reference.md

This is a start towards adding some relay docs.  It's just been copied from the example config.

Add relay docs

---

.prettierrc.cjs
README.md
astro.config.mjs
docs/config/cipher.mdx
docs/config/firewall.mdx
docs/config/lighthouse.mdx
docs/config/listen.mdx
docs/config/local-range.mdx
docs/config/pki.mdx
docs/config/punchy.mdx
docs/config/relay.mdx
docs/config/sshd.mdx
docs/config/static-host-map.mdx
docs/config/tun.mdx
docs/guides/quick-start/index.mdx
docs/guides/unsafe_routes/index.mdx
docs/intro.md
src/css/theme.css

Format with prose wrap always

---

docusaurus.config.cjs
src/css/theme.css

Unfortunately there doesn't seem to be a way to test this other than shipping it to prod.  So, let's :doitlive:!

Add Algolia search

---

.gitignore
package-lock.json
package.json

`npx taze@latest -I`
[postcss-nesting](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-nesting/CHANGELOG.md)
[prettier](https://github.com/prettier/prettier/blob/main/CHANGELOG.md)
[docusaurus](https://docusaurus.io/changelog/2.2.0)
[autoprefixer](https://github.com/postcss/autoprefixer/blob/main/CHANGELOG.md)
some others i haven't listed

Upgrade deps other than MDX & React

---

docusaurus.config.cjs

We only link to slackhq/nebula currently

Add nebula docs source to footer

---

docs/config/pki.mdx

This closes out the documentation task https://github.com/slackhq/nebula/issues/304.

Add note about blocklist distribution

---

docs/guides/quick-start/index.mdx
docs/guides/sign-certificates-with-public-keys/index.md
docs/guides/sign-certificates-with-public-keys/index.mdx

This guide is meant to address https://github.com/slackhq/nebula/issues/76.

Create guide for signing certs with public keys

---

docs/guides/using-lighthouse-dns/ValidateDomainInput.tsx

Fixes https://github.com/DefinedNet/nebula-docs/issues/80
Test by going to https://deploy-preview-85--nebula-docs-dn.netlify.app/docs/guides/using-lighthouse-dns/#hostname-validity, entering a domain and pressing enter. The page should not reload

Prevent default form behavior

---

docs/config/lighthouse.mdx
docs/config/logging.mdx
docs/config/routines.mdx
docs/config/stats.mdx
docs/config/tun.mdx

trying to improve on these listed descriptions mildly

Add some basic descriptions for docs pages

---

package-lock.json
package.json

- https://docusaurus.io/blog/releases/2.3
- https://docusaurus.io/changelog/2.3.0

Update all the things, mainly docusaurus bits

---

docs/guides/using-lighthouse-dns/index.mdx

the lighthouse self-resolve issue has been closed as a duplicate - pointing the page at the current issue to track.

Fix issue number

---

docs/guides/quick-start/index.mdx

We can wait until v1.7.0 releases to merge this one.

Add note about encrypting CA private key

---

docs/config/cipher.mdx
docs/config/firewall.mdx
docs/config/handshake.mdx
docs/config/lighthouse.mdx
docs/config/listen.mdx
docs/config/local-range.mdx
docs/config/pki.mdx
docs/config/preferred-ranges.mdx
docs/config/punchy.mdx
docs/config/relay.mdx
docs/config/sshd.mdx
docs/config/static-host-map.mdx
docs/config/static-map.mdx
docs/config/stats.mdx
docs/config/tun.mdx

@apalrd submitted an excellent PR adding documentation around many previously undocumented options in #102. This PR makes a few nitpick changes to things like the meta descriptions, grammar, and adds a couple clarifying notes.

Followup nitpick changes

---

docs/config/relay.mdx

Much of this is borrowed from https://github.com/slackhq/nebula/pull/678#issuecomment-1180607583

Add more details to the relay docs

---

.github/workflows/ci.yaml
docs/guides/rotating-certificate-authority/index.mdx

[How to rotate to a new certificate authority](https://deploy-preview-108--nebula-docs-dn.netlify.app/docs/guides/rotating-certificate-authority/)

Add CA rotation guide

---

docs/guides/quick-start/index.mdx

This way they have docs to link in their calendar event.

Link to rotation guide from quick start guide

---

docs/config/stats.mdx
src/components/Pill/Pill.module.css

|Before|After|
|---|---|
|<img width="304" alt="image" src="https://github.com/DefinedNet/nebula-docs/assets/4616705/68dea705-ff65-470c-8cad-5281aa900bc0">|<img width="323" alt="image" src="https://github.com/DefinedNet/nebula-docs/assets/4616705/ec16099a-f46d-46ee-808d-c1c3a9ce9bc7">|

Fix stats pills styling

---

docs/config/firewall.mdx
docs/guides/quick-start/index.mdx

Apparently I had another local commit too... link to rotation guide from quick start guide.

Clarify local_cidr evaluation

---

docs/guides/unsafe_routes/index.mdx

Thanks @ieugen for the nftables instructions.

Add ufw and nftables unsafe_routes instructions
